version: "3"
services:
  couchbase-db-0:
    container_name: couchbase1
    image: couchbase
    # deploy:
    #   replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./couchbase/data:/opt/couchbase/var/lib/couchbase/data
      - ./demo/:/mnt/data
      - ./curl_whitelist.json:/opt/couchbase/var/lib/couchbase/n1qlcerts/curl_whitelist.json
      - ./couchbase/node1:/opt/couchbase/var

    # environment:
    #   TYPE: "MASTER"
    # networks:
    #   - couchbase
  couchbase-db-1:
    container_name: couchbase2
    image: couchbase
    volumes:
      - ./couchbase/node1:/opt/couchbase/var
  couchbase-db-2:
    container_name: couchbase3
    image: couchbase
    volumes:
      - ./couchbase/node2:/opt/couchbase/var
  # sync-gateway:
  #   image: couchbase/sync-gateway:1.4.0-2
  #   ports:
  #     - "4984"
  #   volumes:
  #     - ./sync-gateway-config.json:/etc/sync_gateway/config.json
  #   networks:
  #     - couchbase
# networks:
#   couchbase:
#     # driver: overlay
